# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/workspace/Drone/FlightController/hdl/ip/sqrt/sqrt.xci
# IP: The module: 'sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/workspace/Drone/FlightController/hdl/ip/sqrt/sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/workspace/Drone/FlightController/hdl/ip/sqrt/sqrt.xci
# IP: The module: 'sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/workspace/Drone/FlightController/hdl/ip/sqrt/sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
